CREATE TABLE IF NOT EXISTS flux_schema (version integer PRIMARY KEY CHECK (version = 1));
CREATE TABLE workspaces (id text PRIMARY KEY, name text NOT NULL CHECK (length(name) BETWEEN 1 AND 120));
CREATE TABLE memberships (workspace_id text NOT NULL REFERENCES workspaces(id), subject text NOT NULL, role text NOT NULL CHECK (role IN ('viewer','member','admin')), PRIMARY KEY(workspace_id,subject));
CREATE TABLE projects (id text PRIMARY KEY, workspace_id text NOT NULL REFERENCES workspaces(id), name text NOT NULL, revision bigint NOT NULL DEFAULT 1, UNIQUE(workspace_id,id));
-- One board per project; project revision serializes all board decisions.
CREATE TABLE board_columns (project_id text NOT NULL REFERENCES projects(id), id text NOT NULL, name text NOT NULL, category text NOT NULL CHECK (category IN ('todo','doing','done')), position integer NOT NULL, wip integer NOT NULL CHECK (wip >= 0), PRIMARY KEY(project_id,id));
CREATE TABLE sprints (project_id text NOT NULL REFERENCES projects(id), id text NOT NULL, name text NOT NULL, goal text NOT NULL, start_date date NOT NULL, end_date date NOT NULL CHECK (end_date >= start_date), state text NOT NULL CHECK (state IN ('planned','active','closed')), revision bigint NOT NULL, PRIMARY KEY(project_id,id));
CREATE UNIQUE INDEX one_active_sprint ON sprints(project_id) WHERE state='active';
CREATE TABLE work_items (project_id text NOT NULL, workspace_id text NOT NULL, id text NOT NULL, title text NOT NULL, description text NOT NULL, column_id text NOT NULL, sprint_id text, assignee text, priority text NOT NULL CHECK (priority IN ('urgent','high','normal','low')), rank integer NOT NULL, revision bigint NOT NULL, archived boolean NOT NULL, PRIMARY KEY(project_id,id), FOREIGN KEY(workspace_id,project_id) REFERENCES projects(workspace_id,id), FOREIGN KEY(project_id,column_id) REFERENCES board_columns(project_id,id), FOREIGN KEY(project_id,sprint_id) REFERENCES sprints(project_id,id), FOREIGN KEY(workspace_id,assignee) REFERENCES memberships(workspace_id,subject));
CREATE TABLE item_labels (project_id text NOT NULL, item_id text NOT NULL, label text NOT NULL, PRIMARY KEY(project_id,item_id,label), FOREIGN KEY(project_id,item_id) REFERENCES work_items(project_id,id));
CREATE TABLE dependencies (project_id text NOT NULL, item_id text NOT NULL, depends_on text NOT NULL, CHECK(item_id <> depends_on), PRIMARY KEY(project_id,item_id,depends_on), FOREIGN KEY(project_id,item_id) REFERENCES work_items(project_id,id), FOREIGN KEY(project_id,depends_on) REFERENCES work_items(project_id,id));
CREATE TABLE closed_sprint_scope (project_id text NOT NULL, sprint_id text NOT NULL, item_id text NOT NULL, PRIMARY KEY(project_id,sprint_id,item_id), FOREIGN KEY(project_id,sprint_id) REFERENCES sprints(project_id,id), FOREIGN KEY(project_id,item_id) REFERENCES work_items(project_id,id));
CREATE TABLE work_item_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), revision bigint NOT NULL, actor text NOT NULL, action text NOT NULL, target text NOT NULL, reason text NOT NULL, at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, workspace_id text NOT NULL REFERENCES workspaces(id), project_id text REFERENCES projects(id), actor text NOT NULL, action text NOT NULL, request_id text NOT NULL, before_state jsonb, after_state jsonb, outcome text NOT NULL, at timestamptz NOT NULL DEFAULT now());
CREATE TABLE idempotency_keys (project_id text NOT NULL REFERENCES projects(id), actor text NOT NULL, key text NOT NULL, digest text NOT NULL, revision bigint NOT NULL, PRIMARY KEY(project_id,actor,key));
CREATE INDEX item_order ON work_items(project_id,rank,id);
CREATE INDEX event_history ON work_item_events(project_id,id DESC);
INSERT INTO flux_schema(version) VALUES(1);
